spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.30.50.22/navinfo_wedrive
    username: linshi
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
